apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pg-backup-every-twelve-hours
spec:
  schedule: "0 */12 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: pgsql-backup
              image: icereed/postgres-backup-s3-container:latest
              env:
                - name: PGHOST
                  value: "PGHOST_PLACEHOLDER"
                - name: PGPORT
                  value: "PGPORT_PLACEHOLDER"
                - name: PGDATABASE
                  value: "PGDATABASE_PLACEHOLDER"
                - name: PGUSER
                  value: "PGUSER_PLACEHOLDER"
                - name: PGPASSWORD
                  value: "PGPASSWORD_PLACEHOLDER"
                - name: S3_BUCKET
                  value: "S3_BUCKET_PLACEHOLDER"
